### ISSUE TITLE
Duplicated line

### ISSUE THREAD

**Issue by ManUtopiK** [fumeapp/dayjs#1]
The plugin is added two times with `addPlugin(resolver.resolve('runtime/plugin.client'))`.
Line [L40](https://github.com/fumeapp/dayjs/blob/main/src/module.ts#L40) and [L46](https://github.com/fumeapp/dayjs/blob/main/src/module.ts#L46)

**Comment by acidjazz** [comment]
Thank you!! this is still in pretty early development - I'll KYP for when it's ready!
