### ISSUE TITLE
README.md content issue 

### ISSUE THREAD

**Issue by jeevanya** [fumeapp/dayjs#10]
Hi,
can you please update this tag mistake.
![image](https://github.com/fumeapp/dayjs/assets/103981778/acbfaf5b-8a9a-46d1-a040-a2686a075ac0)

**Comment by acidjazz** [comment]
sure, also PR's are welcome :)

**Comment by jeevanya** [comment]
Hi @acidjazz,
PR for readme content update: https://github.com/fumeapp/dayjs/pull/12
can you please review and merge it.
