### ISSUE TITLE
useDayjs missing from export

### ISSUE THREAD

**Issue by GaborTorma** [fumeapp/dayjs#18]
Can't use useDayjs when autoimport is disabled.
I've got the following error message: Missing "./dist/runtime/composables/dayjs" specifier in "dayjs-nuxt" package

I tried three ways: 
```ts
import { useDayjs } from '#dayjs'
   // Cannot find module '#dayjs' or its corresponding type declarations.

import { useDayjs } from 'dayjs-nuxt'
   // Module '"dayjs-nuxt"' has no exported member 'useDayjs'.

import { useDayjs } from 'dayjs-nuxt/dist/runtime/composables/dayjs'
   // no typescript error message, but has runtime error:  ERROR  Missing "./dist/runtime/composables/dayjs" specifier in "dayjs-nuxt" package 
```

**Comment by acidjazz** [comment]
how did you disabled autoimports?

**Comment by GaborTorma** [comment]
in ,nuxtrc file: https://github.com/nuxt/starter/blob/module/.nuxtrc#L1
It's need for module developing: https://nuxt.com/docs/guide/going-further/modules#module-anatomy:~:text=Published%20modules%20cannot,your%20playground%20either.

**Comment by acidjazz** [comment]
well i'm not sure its missing from the exports since the autoImport does work.

on my playground i can import it locally like this:

```ts
import { useDayjs } from '../src/runtime/composables';
```

i wonder if you can specify it somehow locally

**Comment by GaborTorma** [comment]
Yes, locally in your modul works. You need to install a modul to a clear nuxt workspace.
You can test it on my Stackblitz demo: https://stackblitz.com/edit/nuxt-starter-ilmx38?file=app.vue

**Comment by acidjazz** [comment]
@GaborTorma try:

```ts
import { useDayjs } from '#imports"
```


using https://github.com/fumeapp/dayjs/releases/tag/v1.2.7

**Comment by GaborTorma** [comment]
It works. Thanx!
