### ISSUE TITLE
Nuxt 2 support

### ISSUE THREAD

**Issue by ineshbose** [fumeapp/dayjs#2]
Hi! Thanks for this module

Do you think providing compatibility for Nuxt 2 could be possible? That would make this module incredible.

Check out the code for [tailwindcss module](https://github.com/nuxt-modules/tailwindcss) for how it provides compatibility for both Nuxt 2 and 3 from a single codebase. 🙂

**Comment by acidjazz** [comment]
I will take a look and see how much effort it will be but right now I'll say it's doubtful
