### ISSUE TITLE
updateLocale is not defined

### ISSUE THREAD

**Issue by Corentin7301** [fumeapp/dayjs#22]
Hi!
I've a `500` error : `updateLocale is not defined` when I run the Nuxt server.

Look at the Nuxt config:
```
modules: ['dayjs-nuxt'],
dayjs: {
    locales: ['fr'],
    plugins: ['relativeTime', 'utc', 'timezone'],
    defaultLocale: 'fr',
    defaultTimezone: 'Europe/Paris',
  },
```

The error disappears when I delete the configuration `dayjs: {...}`.

Node: v20.8.0
Nuxt: 3.7.4
Nuxt: SSR
dayjs-nuxt: 2.0.2

**Comment by Corentin7301** [comment]
The error disappears when I comment `defaultLocale`.

**Comment by bennyzen** [comment]
Same error here. The `defaultLocale` in `nuxt.config.js` seems to be the culprit. Commenting it out apparently fixes the issue.
