### ISSUE TITLE
Not compatible with String + Format plugin

### ISSUE THREAD

**Issue by nicolashmln** [fumeapp/dayjs#24]
The composable accepts only one argument. If you install the [CustomParseFormat](https://day.js.org/docs/en/parse/string-format) dayjs can accept 2 to 4 arguments.

Would you recommend to not use the composable in that case? Or you can integrate it in the composable?

Thanks

**Comment by acidjazz** [comment]
hmmmmmmm

**Comment by acidjazz** [comment]
maybe try adding 3+ more optional parameters to the composable locally and see if that works? if so PR that here

**Comment by acidjazz** [comment]
i no longer execute dayjs in the composable, try https://github.com/fumeapp/dayjs/releases/tag/v2.1.1

**Comment by acidjazz** [comment]
try the latest @nicolashmln
