### ISSUE TITLE
defaultLocale and browser local setting those are not working.

### ISSUE THREAD

**Issue by quroom** [fumeapp/dayjs#27]
https://stackblitz.com/edit/nuxt-starter-rstvii?file=app.vue

Look, I set defaultLocale as ko
But fromNow doesn't return time with ko locale.

And it also doesn't reflect browser locale setting.

**Comment by acidjazz** [comment]
> https://stackblitz.com/edit/nuxt-starter-rstvii?file=app.vue
> 
> Look, I set defaultLocale as ko But fromNow doesn't return time with ko locale.
> 
> And it also doesn't reflect browser locale setting.

You are only setting the locale for that one line in the component, you need to set it in your nuxt config if it you want it global, or have a composable return it w/ that locale

**Comment by quroom** [comment]
@acidjazz 
Thanks for quick response!

I am not sure what I unserstand correctly.

1. "you need to set it in your nuxt config if it you want it global"
-> I set it as "ko" in nuxt.config.ts , you can check it in the link. So I expect 
This code```useDayjs()('2023-01-01').fromNow()``` returns "10 달 전" 
But it returns 10 months ago. It isn't ko locale.. Isn't it?

2. "have a composable return it w/ that locale"
I am not sure how I can make code as you said.

**Comment by acidjazz** [comment]
@quroom i did not see you set it up in your nuxt config, looking into this now..

**Comment by acidjazz** [comment]
fixed in https://github.com/fumeapp/dayjs/releases/tag/v2.1.7

**Comment by quroom** [comment]
@acidjazz 
Thanks for answering.
```
nuxt.config.ts

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: ['dayjs-nuxt'],
  dayjs: {
    locales: ['ko', 'en'],
    plugins: ['relativeTime', 'utc', 'timezone'],
    defaultLocale: 'ko',
    defaultTimezone: 'Asia/Seoul',
  },
});

```
I added this code in nuxt.config.ts
```
defaultLocale: 'ko',
```
Isn't it for setting defaultLocale?
If it isn't, could you make it correct?

![image](https://github.com/fumeapp/dayjs/assets/39736691/602cbf4c-64dc-4728-898f-6d673324e8ee)

Anyway I will try same thing with v2.1.7 and leave comment ASAP

Updated.
defaultLocale looks working well in 2.1.7 version.
But I want to make what I understand clear.
If I didn't understand correctly, make me clear.
It's only possible setting global default locale in nuxt.config.
If I want to make locale updated with local browser language setting, I need to make composable to support it.
Is that right?

Then why don't it support update locale automatically based on user's locale based on might be browser?
It can be supported by optional.
