### ISSUE TITLE
Uncaught SyntaxError: import not found: default

### ISSUE THREAD

**Issue by pmnzt** [fumeapp/dayjs#38]
Just installed dayjs-nuxt and added it to modules Now getting that error in the console.
relevant details about the project in this repo: https://github.com/pmnzt/nuxt-dayjs-issue.

OS: Debian 12 bookworm
Browser: FireFox Stable  123.0.1

**Comment by pmnzt** [comment]
For anyone still getting this error, i have talked to acidjazz over on discord.. and his reply was:
> try doing pnpm add -D dayjs

and that did fix the error for me.. i hadn't received anything on this issue yet. but for now that's a way to solve this issue.

**Comment by tcampbPPU** [comment]
yes adding both is required for example `package.json` file:
```json
  "devDependencies": {
    "dayjs": "^1.11.11",
    "dayjs-nuxt": "^2.1.9"
  }
```
