### ISSUE TITLE
ts error

### ISSUE THREAD

**Issue by transtone** [fumeapp/dayjs#4]
'dayjs' does not exist in type 'InputConfig<NuxtConfig, ConfigLayerMeta>'

![image](https://github.com/fumeapp/dayjs/assets/46688/5d6b1dbf-79c0-46e0-b94d-a3067a0c5ba1)

**Comment by acidjazz** [comment]
what version of nuxt are you using? can i see your `nuxt.config.ts` ?

**Comment by acidjazz** [comment]
grab v1.1.2 and you should be good!

<img width="843" alt="image" src="https://github.com/fumeapp/dayjs/assets/967369/35b3d8ca-12cf-4ea1-a529-6237faf98d2a">
