### ISSUE TITLE
relativeTime thresholds options?

### ISSUE THREAD

**Issue by Extarys** [fumeapp/dayjs#5]
I need to update `thresholds` for the `relativeTime` plugin, and update `updateLocale` accordingly.

https://day.js.org/docs/en/customization/relative-time

Is it possible with this plugin / is it hard to implement?

**Comment by acidjazz** [comment]
no problem, i'll have this in shortly

**Comment by Extarys** [comment]
Thank you, Sensei!

**Comment by acidjazz** [comment]
grab v1.1.2 and you should be all set https://github.com/fumeapp/dayjs#optional-relativetime-customization

**Comment by Extarys** [comment]
Wow, thanks @acidjazz !
I don't mean to offend you and the free work you're doing, but is it planned to also add `thresholds` eventually? :)

**Comment by acidjazz** [comment]
is that this? https://day.js.org/docs/en/customization/relative-time#relative-time-thresholds-and-rounding

**Comment by Extarys** [comment]
Yes this is it :P

**Comment by rafaelragib** [comment]
Hey @acidjazz!
Thanks for the awesome work. Could you give an update about the integration of thresholds? I am not able to add it using the `updateLocale`
Thanks!

**Comment by GaborTorma** [comment]
> Hey @acidjazz! Thanks for the awesome work. Could you give an update about the integration of thresholds? I am not able to add it using the `updateLocale` Thanks!

You can extend with configuration via nuxt plugin like this: [More Extending](https://github.com/fumeapp/dayjs#more-extending)
If you need automatic i18n support, you can use my [nuxt-dayjs-i18n](https://www.npmjs.com/package/@gabortorma/nuxt-dayjs-i18n) module.

**Comment by rafaelragib** [comment]
```typescript
 dayjs: {
      locales: ['en'],
      plugins: ['relativeTime', 'utc', 'timezone'],
      defaultLocale: [ 'en', {
        thresholds: [
          { l: 's', r: 1 },
          { l: 'm', r: 1 },
          { l: 'mm', r: 59, d: 'minute' },
          { l: 'h', r: 1 },
          { l: 'hh', r: 23, d: 'hour' },
          { l: 'd', r: 1 },
          { l: 'dd', r: 29, d: 'day' },
          { l: 'M', r: 1 },
          { l: 'MM', r: 11, d: 'month' },
          { l: 'y' },
          { l: 'yy', d: 'year' }
        ]
      }]
    },
``` 
Not working for my side.  Not sure what I am doing wrong here. (Changing the 45 minutes to 59 minutes)

**Comment by GaborTorma** [comment]
@rafaelragib: I think defaultLocale has no thresholds option.
You need to pass it to relativeTime options in extend.

```js
// plugins/relative-time.plugin.ts
import relativeTime from 'dayjs/plugins/relativetime'  // I'm not sure the import statement.

export default defineNuxtPlugin(() => {
  useDayjs().extend(relativeTime, {
    thresholds: [
      { l: 's', r: 1 },
      { l: 'm', r: 1 },
      { l: 'mm', r: 59, d: 'minute' },
      { l: 'h', r: 1 },
      { l: 'hh', r: 23, d: 'hour' },
      { l: 'd', r: 1 },
      { l: 'dd', r: 29, d: 'day' },
      { l: 'M', r: 1 },
      { l: 'MM', r: 11, d: 'month' },
      { l: 'y' },
      { l: 'yy', d: 'year' },
    ],
  })
})
```

**Comment by rafaelragib** [comment]
Thanks @GaborTorma ! I have added the changes you have suggested  
```typescript
import relativeTime from 'dayjs/plugin/relativeTime';

export default defineNuxtPlugin(() => {
  useDayjs().extend(relativeTime, {
    thresholds: [
      { l: 's', r: 1 },
      { l: 'm', r: 1 },
      { l: 'mm', r: 59, d: 'minute' },
      { l: 'h', r: 1 },
      { l: 'hh', r: 23, d: 'hour' },
      { l: 'd', r: 1 },
      { l: 'dd', r: 29, d: 'day' },
      { l: 'M', r: 1 },
      { l: 'MM', r: 11, d: 'month' },
      { l: 'y' },
      { l: 'yy', d: 'year' }
    ]
  });
});
```
The thresholds is still not being set. It is getting the default 45 minutes still. 
```typescript
const publishTimeFromNow = computed(() => {
  return dayjs(publication_time_utc).utc().fromNow();
}); 
```

**Comment by demyan1411** [comment]
Not works for me =(

**Comment by mkody** [comment]
Suggested changes using `useDayjs().extend()` in `plugins/` doesn't work. 
This issue should be reopened, only half of it is done.
