### ISSUE TITLE
 The requested module '/_nuxt/node_modules/.pnpm/dayjs@1.11.13/node_modules/dayjs/dayjs.min.js?v=cdf6ee2a' does not provide an export named 'default'

### ISSUE THREAD

**Issue by lixiao258** [fumeapp/dayjs#53]
The requested module '/_nuxt/node_modules/.pnpm/dayjs@1.11.13/node_modules/dayjs/dayjs.min.js?v=cdf6ee2a' does not provide an export named 'default'
![微信截图_20240830113013](https://github.com/user-attachments/assets/11d9488d-60eb-4d9e-ac01-107a2879e0f3)

{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "@nuxtjs/robots": "^4.1.3",
    "dayjs-nuxt": "^2.1.11",
    "nuxt": "^3.12.4",
    "vue": "latest"
  }
}

**Comment by trihargianto** [comment]
Hi @lixiao258, I got the same error. What was your solution for this?

**Comment by lixiao258** [comment]
> 你好@lixiao258，我遇到了同样的错误。你对此有什么解决方案？

pnpm install dayjs

**Comment by trihargianto** [comment]
> pnpm install dayjs

ok. thank you

**Comment by bbhxwl** [comment]
I also have the same problem
