### ISSUE TITLE
useDayjs() returns an any

### ISSUE THREAD

**Issue by jakubkoje** [fumeapp/dayjs#6]
Hey, I tried to use your module in my project, but I can not successfully get the right types inside of my Nuxt project. It is always any, no matter what I do.

**Comment by acidjazz** [comment]
I'll have a fix for this out by tomorrow

**Comment by acidjazz** [comment]
grab v1.1.2 and you should be good!

<img width="843" alt="image" src="https://github.com/fumeapp/dayjs/assets/967369/35b3d8ca-12cf-4ea1-a529-6237faf98d2a">
