### ISSUE TITLE
Issue: dayjs Plugin Not Working on Server Side in Nuxt

### ISSUE THREAD

**Issue by ducmanhdev** [fumeapp/dayjs#62]
After registering the required Day.js plugins in my Nuxt 3 project, the plugins function correctly on the client side but fail to work properly on the server side. Specifically, I encounter the following error when using certain plugin methods on the server:

`dayjs(...).isSameOrAfter is not a function`

However, my IDE correctly recognizes the method, and the code appears valid (e.g., autocompletion works, and there are no TypeScript or syntax errors). This discrepancy only occurs during server-side execution.

```
// nuxt.config.ts
export default defineNuxtConfig({
  modules: ['dayjs-nuxt'],
  dayjs: {
    plugins: ['isSameOrAfter'], // Plugins registered
  },
});
```

**Environment**
- "nuxt": "3.14.1592",
- "dayjs": "^1.11.13",
- "dayjs-nuxt": "^2.1.11",

**Comment by Norbiros** [comment]
@ducmanhdev how you managed to solve this issue? Because I think I am experiencing the same thing now...

**Comment by ducmanhdev** [comment]
@Norbiros , Hi, about the problem, I initially reported this issue as a server-side problem, but I was mistaken. The root cause was actually how I was using dayjs outside of the Nuxt.js context, specifically within a utility file.

To resolve this, I imported dayjs and the necessary plugins directly into the utility file, ensuring they are used within that specific context.

**Comment by deepfriedmind** [comment]
I'm getting the same 500 error in a Nuxt page file when using `duration`, so it is within the Nuxt context. `TypeError: dayjs.duration is not a function`. I do have `duration` added in the Nuxt config:
```js
dayjs: {
  plugins: ['duration'],
}
```

If I add this in `app.vue`, it works:
```js
import dayjs from 'dayjs'
import duration from 'dayjs/plugin/duration'

dayjs.extend(duration)
```
