### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by davide-granello** [fumeapp/dayjs#7]
Hello, no types are defined for the `$dayjs` plugin.
<img width="350px" alt="image" src="https://github.com/fumeapp/dayjs/assets/82588489/3cda9216-6e96-460c-b02f-3767fb04adfc">

Do you plan to support typescript?

**Comment by acidjazz** [comment]
Yup! Fix coming soon!

**Comment by acidjazz** [comment]
grab v1.1.2 and you should be good!

<img width="843" alt="image" src="https://github.com/fumeapp/dayjs/assets/967369/35b3d8ca-12cf-4ea1-a529-6237faf98d2a">
