### ISSUE TITLE
Doesn't work in server directory

### ISSUE THREAD

**Issue by lukas-schaetzle** [fumeapp/dayjs#8]
Thanks for the module. It works for normal components/pages etc. but when I want to use the `useDayjs` composable in the server directory I always run into the error

```
[nuxt] [request error] [unhandled] [500] useDayjs is not defined
```

**Comment by acidjazz** [comment]
I'm not quite sure you have access to any composables in the server directory @Tummerhore

I believe I found out about this writing https://fume.app/blog/nuxt-3-api-captcha

Don't quote me on that but I recall having to work around this type of issue, I think you're limited to everything specified in the examples [here](https://nuxt.com/docs/guide/directory-structure/server)

**Comment by lukas-schaetzle** [comment]
Ah, too bad. Would be nice to have a small disclaimer in the readme since I find the limitations in the server directory are not clearly communicated in nuxt's docs (for example the `useRuntimeConfig` composable can be used).

Do you happen to know how one could use dayjs in a server api route? When I try to import the dayjs plugins manually in a file in the server directory (like this: `import relativeTime from "dayjs/plugin/relativeTime"`), the imported modules are not found when running the built server:

```
Cannot find module '/Users/.../project-folder/.output/server/node_modules/dayjs/plugin/relativeTime' imported from /Users/.../project-folder/.output/server/chunks/api-test.post.mjs
Did you mean to import dayjs/plugin/relativeTime.js?
```

I guess there's some problem with how rollup handles the imports but I have no idea how to fix it.

**Comment by acidjazz** [comment]
No but you might find better luck asking [here](https://github.com/nuxt/nuxt/discussions) feel free to report back here - It would be nice to know a way to share such thing with `/server`
