### ISSUE TITLE
Cannot build in prod with Nuxt typescript typecheck option enabled

### ISSUE THREAD

**Issue by agenordebriat** [fumeapp/dayjs#9]
I added the module (1.1.2) to my project (Nuxt 3.5.3) and noticed my build pipeline failed with the following error:
`Property 'fromNow' does not exist on type 'Dayjs'`

It happens when I enable the typescript typecheck option in nuxt.config.ts and/or use the following vite config:
```ts
vite: {
  plugins: [checker({ eslint: { lintCommand: "eslint ." }, vueTsc: true })],
},
```

For now, I disabled both and I typecheck manually.

dayjs config in nuxt.config.ts is:
```ts
dayjs: {
  locales: ["fr"],
  plugins: ["relativeTime", "timezone", "utc"],
  defaultTimezone: "Europe/Paris",
},
```

**Comment by acidjazz** [comment]
I'll take a look, if you can provide an example environment rep/sandbox/etc that could definitely speed things up

**Comment by acidjazz** [comment]
try the latest @agenordebriat
